{{- if .Values.apiSettings.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "teams-api-rbac.service-account-name" . }}
  namespace: {{ .Values.namespace.name }}
  {{- with .Values.apiSettings.rbac.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "teams-api-rbac.service-account-labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
